# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_scannergui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1440, 864)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.action_scanner_settings = QAction(MainWindow)
        self.action_scanner_settings.setObjectName(u"action_scanner_settings")
        icon = QIcon()
        icon.addFile(u"../../../../../../../../Software/qudivenv/src/qudi/qudi/core/artwork/icons/configure.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.action_scanner_settings.setIcon(icon)
        self.action_close_window = QAction(MainWindow)
        self.action_close_window.setObjectName(u"action_close_window")
        icon1 = QIcon()
        icon1.addFile(u"../../../../../../../../Software/qudivenv/src/qudi/qudi/core/artwork/icons/application-exit.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.action_close_window.setIcon(icon1)
        self.action_optimizer_settings = QAction(MainWindow)
        self.action_optimizer_settings.setObjectName(u"action_optimizer_settings")
        self.action_optimizer_settings.setIcon(icon)
        self.action_utility_zoom = QAction(MainWindow)
        self.action_utility_zoom.setObjectName(u"action_utility_zoom")
        self.action_utility_zoom.setCheckable(True)
        icon2 = QIcon()
        icon2.addFile(u"../../../../../../../../Software/qudivenv/src/qudi/qudi/core/artwork/icons/zoom-select.svgz", QSize(), QIcon.Normal, QIcon.Off)
        icon2.addFile(u"../../../../../../../../Software/qudivenv/src/qudi/qudi/core/artwork/icons/search_active.svg", QSize(), QIcon.Normal, QIcon.On)
        self.action_utility_zoom.setIcon(icon2)
        self.action_view_scanner_control = QAction(MainWindow)
        self.action_view_scanner_control.setObjectName(u"action_view_scanner_control")
        self.action_view_scanner_control.setCheckable(True)
        self.action_view_scanner_control.setChecked(True)
        self.action_view_optimizer = QAction(MainWindow)
        self.action_view_optimizer.setObjectName(u"action_view_optimizer")
        self.action_view_optimizer.setCheckable(True)
        self.action_view_optimizer.setChecked(True)
        self.action_optimize_position = QAction(MainWindow)
        self.action_optimize_position.setObjectName(u"action_optimize_position")
        self.action_optimize_position.setCheckable(True)
        self.action_optimize_position.setEnabled(True)
        icon3 = QIcon()
        icon3.addFile(u"../../core/artwork/icons/optimize-position.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon3.addFile(u"../../core/artwork/icons/scan-stop.svg", QSize(), QIcon.Normal, QIcon.On)
        self.action_optimize_position.setIcon(icon3)
        self.action_restore_default_view = QAction(MainWindow)
        self.action_restore_default_view.setObjectName(u"action_restore_default_view")
        self.action_history_forward = QAction(MainWindow)
        self.action_history_forward.setObjectName(u"action_history_forward")
        self.action_history_forward.setEnabled(True)
        icon4 = QIcon()
        icon4.addFile(u"../../../../../../../../Software/qudivenv/src/qudi/qudi/core/artwork/icons/go-next.svgz", QSize(), QIcon.Normal, QIcon.Off)
        self.action_history_forward.setIcon(icon4)
        self.action_history_back = QAction(MainWindow)
        self.action_history_back.setObjectName(u"action_history_back")
        self.action_history_back.setEnabled(True)
        icon5 = QIcon()
        icon5.addFile(u"../../../../../../../../Software/qudivenv/src/qudi/qudi/core/artwork/icons/go-previous.svgz", QSize(), QIcon.Normal, QIcon.Off)
        self.action_history_back.setIcon(icon5)
        self.action_view_line_scan = QAction(MainWindow)
        self.action_view_line_scan.setObjectName(u"action_view_line_scan")
        self.action_view_line_scan.setCheckable(True)
        self.action_view_line_scan.setChecked(True)
        self.action_utility_full_range = QAction(MainWindow)
        self.action_utility_full_range.setObjectName(u"action_utility_full_range")
        icon6 = QIcon()
        icon6.addFile(u"../../../../../../../../Software/qudivenv/src/qudi/qudi/core/artwork/icons/zoom-fit-best.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.action_utility_full_range.setIcon(icon6)
        self.action_autorange_2d_scans = QAction(MainWindow)
        self.action_autorange_2d_scans.setObjectName(u"action_autorange_2d_scans")
        self.action_autorange_2d_scans.setCheckable(False)
        self.action_display_settings = QAction(MainWindow)
        self.action_display_settings.setObjectName(u"action_display_settings")
        self.action_display_settings.setIcon(icon)
        self.action_view_toolbar = QAction(MainWindow)
        self.action_view_toolbar.setObjectName(u"action_view_toolbar")
        self.action_view_toolbar.setCheckable(True)
        self.action_view_toolbar.setChecked(True)
        self.action_save_all_scans = QAction(MainWindow)
        self.action_save_all_scans.setObjectName(u"action_save_all_scans")
        icon7 = QIcon()
        icon7.addFile(u"../../../../../qudi-core/src/qudi/artwork/icons/document-save.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.action_save_all_scans.setIcon(icon7)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMaximumSize(QSize(0, 0))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1440, 30))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menu_Settings = QMenu(self.menubar)
        self.menu_Settings.setObjectName(u"menu_Settings")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.util_toolBar = QToolBar(MainWindow)
        self.util_toolBar.setObjectName(u"util_toolBar")
        self.util_toolBar.setAllowedAreas(Qt.LeftToolBarArea|Qt.RightToolBarArea|Qt.TopToolBarArea)
        self.util_toolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.util_toolBar.setFloatable(False)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.util_toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_close_window)
        self.menuFile.addAction(self.action_save_all_scans)
        self.menu_Settings.addAction(self.action_scanner_settings)
        self.menu_Settings.addAction(self.action_optimizer_settings)
        self.menu_Settings.addAction(self.action_display_settings)
        self.menuView.addAction(self.action_view_scanner_control)
        self.menuView.addAction(self.action_view_optimizer)
        self.menuView.addAction(self.action_view_toolbar)
        self.menuView.addAction(self.action_view_line_scan)
        self.menuView.addSeparator()
        self.menuView.addAction(self.action_restore_default_view)
        self.menuView.addSeparator()
        self.menuView.addAction(self.action_autorange_2d_scans)
        self.util_toolBar.addAction(self.action_optimize_position)
        self.util_toolBar.addAction(self.action_utility_zoom)
        self.util_toolBar.addAction(self.action_utility_full_range)
        self.util_toolBar.addSeparator()
        self.util_toolBar.addAction(self.action_history_back)
        self.util_toolBar.addAction(self.action_history_forward)

        self.retranslateUi(MainWindow)
        self.action_close_window.triggered.connect(MainWindow.close)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"qudi: Confocal", None))
        self.action_scanner_settings.setText(QCoreApplication.translate("MainWindow", u"Scan Settings", None))
        self.action_close_window.setText(QCoreApplication.translate("MainWindow", u"Close window", None))
#if QT_CONFIG(tooltip)
        self.action_close_window.setToolTip(QCoreApplication.translate("MainWindow", u"Close scanning window", None))
#endif // QT_CONFIG(tooltip)
        self.action_optimizer_settings.setText(QCoreApplication.translate("MainWindow", u"Optimizer Settings", None))
        self.action_utility_zoom.setText(QCoreApplication.translate("MainWindow", u"Zoom", None))
#if QT_CONFIG(tooltip)
        self.action_utility_zoom.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle zooming by rubberband selection. Will set scan ranges accordingly.\n"
"Shortcut:Z", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_utility_zoom.setShortcut(QCoreApplication.translate("MainWindow", u"Z", None))
#endif // QT_CONFIG(shortcut)
        self.action_view_scanner_control.setText(QCoreApplication.translate("MainWindow", u"Scanner control", None))
#if QT_CONFIG(tooltip)
        self.action_view_scanner_control.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle scanner control view", None))
#endif // QT_CONFIG(tooltip)
        self.action_view_optimizer.setText(QCoreApplication.translate("MainWindow", u"Optimizer", None))
#if QT_CONFIG(tooltip)
        self.action_view_optimizer.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle optimizer view\n"
"Shortcut:Alt+O", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_view_optimizer.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+O", None))
#endif // QT_CONFIG(shortcut)
        self.action_optimize_position.setText(QCoreApplication.translate("MainWindow", u"Optimize position", None))
#if QT_CONFIG(tooltip)
        self.action_optimize_position.setToolTip(QCoreApplication.translate("MainWindow", u"Optimize scanner position according to the configured procedure\n"
"Shortcut:Ctrl+Alt+X", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_optimize_position.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.action_optimize_position.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+X", None))
#endif // QT_CONFIG(shortcut)
        self.action_restore_default_view.setText(QCoreApplication.translate("MainWindow", u"Restore default", None))
#if QT_CONFIG(tooltip)
        self.action_restore_default_view.setToolTip(QCoreApplication.translate("MainWindow", u"Restore default arrangement of dock widgets ", None))
#endif // QT_CONFIG(tooltip)
        self.action_history_forward.setText(QCoreApplication.translate("MainWindow", u"Forward", None))
#if QT_CONFIG(tooltip)
        self.action_history_forward.setToolTip(QCoreApplication.translate("MainWindow", u"Go forward in scan history\n"
"Shortcut:Ctrl+R", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_history_forward.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.action_history_back.setText(QCoreApplication.translate("MainWindow", u"Backward", None))
#if QT_CONFIG(tooltip)
        self.action_history_back.setToolTip(QCoreApplication.translate("MainWindow", u"Go backwards in scan history\n"
"Shortcut:Ctrl+Z", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_history_back.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.action_view_line_scan.setText(QCoreApplication.translate("MainWindow", u"Line scan", None))
#if QT_CONFIG(tooltip)
        self.action_view_line_scan.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle line scan view", None))
#endif // QT_CONFIG(tooltip)
        self.action_utility_full_range.setText(QCoreApplication.translate("MainWindow", u"Full range", None))
#if QT_CONFIG(tooltip)
        self.action_utility_full_range.setToolTip(QCoreApplication.translate("MainWindow", u"Set all scans to full scan range\n"
"Shortcut:Ctrl+Alt+<", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_utility_full_range.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+<", None))
#endif // QT_CONFIG(shortcut)
        self.action_autorange_2d_scans.setText(QCoreApplication.translate("MainWindow", u"Auto range 2D scans", None))
#if QT_CONFIG(tooltip)
        self.action_autorange_2d_scans.setToolTip(QCoreApplication.translate("MainWindow", u"Automatically adjust axes ranges for 2D scan images\n"
"Shortcut: Shift+R", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_autorange_2d_scans.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+R", None))
#endif // QT_CONFIG(shortcut)
        self.action_display_settings.setText(QCoreApplication.translate("MainWindow", u"Display Settings", None))
        self.action_view_toolbar.setText(QCoreApplication.translate("MainWindow", u"Toolbar", None))
#if QT_CONFIG(tooltip)
        self.action_view_toolbar.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle utility toolbar view\n"
"Shortcut:Alt+T", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_view_toolbar.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+T", None))
#endif // QT_CONFIG(shortcut)
        self.action_save_all_scans.setText(QCoreApplication.translate("MainWindow", u"Save all", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menu_Settings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"&View", None))
        self.util_toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"Utilities Toolbar", None))
    # retranslateUi

